### ISSUE TITLE
Pylance: More than one labels are collected. Defaulting to the first one.

### ISSUE THREAD

**Issue by disrupted** [Davidyz/inlayhint-filler.nvim#4]
First of all thank you so much for this fantastic plugin! I will get a ton of use out of it.

**Describe the bug**
Each time I trigger a fill I get the warning "More than one labels are collected. Defaulting to the first one.". Even on something as basic as `-> None` as shown in the example below. It still works fine, just the message is a bit irritating as if something is amiss.

**To Reproduce**
1. Language server used: Pylance
2. How you setup the language server (preferably with [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig):
unfortunately cannot share here. in case you're unable to reproduce please feel free to close my issue

3. Code snippet that you're editing:
```python
def foo():
    pass
```

**Expected behavior**
succeeds without warning

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS 15.1.1
 - Neovim Version [e.g. v0.10.2 or commit ID] 
> NVIM v0.11.0-dev-5881+g0dd933265f-Homebrew
Build type: Release
LuaJIT 2.1.1732813678

**Additional context**

**Comment by Davidyz** [comment]
Hi thanks for using the plugin! If I remembered correctly, the license of pylance doesn't allow usage outside of vscode and the open source subset of it, pyright, doesn't provide inlayhint. Are you sure you're using pylance? If you can't share instructions for setting up the language server, I don't think I'll be able to reproduce.

**Comment by Davidyz** [comment]
Hi thanks for using the plugin! If I remembered correctly, the license of pylance doesn't allow usage outside of vscode and the open source subset of it, pyright, doesn't provide inlayhint. Are you sure you're using pylance? If you can't share instructions for setting up the language server, I don't think I'll be able to reproduce. 

With that said, if you could post the output of `vim.lsp.inlay_hint.get({bufnr=0})`, I might be able to spot the issue and try to figure out a fix.

**Comment by Davidyz** [comment]
> With that said, if you could post the output of `vim.lsp.inlay_hint.get({bufnr=0})`, I might be able to spot the issue and try to figure out a fix.

The latest commit should help you do this. The output of `vim.lsp.inlay_hint.get` will be included in the notification.

**Comment by disrupted** [comment]
funnily enough now I cannot reproduce it 😄 
thanks for looking into it! I'll reopen the issue if I ever encounter it again
